# Generated by Django 2.0.2 on 2018-06-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=1000)),
                ('text_peticije', models.TextField()),
                ('datum_pocetka', models.DateField()),
                ('datum_zavrsetka', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Potpisane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField()),
                ('id_peticije', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticija.Peticije')),
            ],
        ),
        migrations.CreateModel(
            name='Potpisanti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('prebivaliste', models.CharField(max_length=50)),
                ('jmbg', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='potpisane',
            name='id_potpisanta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticija.Potpisanti'),
        ),
        migrations.AlterUniqueTogether(
            name='potpisane',
            unique_together={('id_peticije', 'id_potpisanta')},
        ),
    ]
