# Generated by Django 2.0.2 on 2018-05-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Potpisane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peticije', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticija.Peticije')),
            ],
        ),
        migrations.CreateModel(
            name='Potpisanti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='potpisane',
            name='id_potpisanta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticija.Potpisanti'),
        ),
        migrations.AlterUniqueTogether(
            name='potpisane',
            unique_together={('id_peticije', 'id_potpisanta')},
        ),
    ]
