# Generated by Django 2.0.2 on 2018-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticije',
            name='broj_potpisa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
